"""comments table

Revision ID: 2e0cd320299e
Revises: 62dc405d5b39
Create Date: 2018-06-20 14:11:16.069133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0cd320299e'
down_revision = '62dc405d5b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    op.drop_column('comments', 'disabled')
    op.drop_column('comments', 'body_html')
    op.drop_column('comments', 'body')
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
