"""redo follow

Revision ID: 62dc405d5b39
Revises: ac9c18e4494e
Create Date: 2018-06-13 11:20:20.958398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dc405d5b39'
down_revision = 'ac9c18e4494e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'timestamp')
    # ### end Alembic commands ###
